export const flaskServerRoot = "http://127.0.0.1:8000/coco/api/v1.0/"
export const addUser = flaskServerRoot + "add_user"
export const register = flaskServerRoot + "register"
export const login = flaskServerRoot + "login"
export const forgot = flaskServerRoot + "forgot"
export const reset = flaskServerRoot + "reset"