export const flaskServerRoot = "http://10.0.2.2:8000/"
export const addUser = flaskServerRoot + "coco/api/v1.0/add_user"
export const register = flaskServerRoot + "register"
export const login = flaskServerRoot + "login"
export const forgot = flaskServerRoot + "forgot"
export const reset = flaskServerRoot + "reset"