export default {
    LOGIN: "Login",
    SIGN_UP: "SignUp",
    DUO: "Duo",
    HOME: "Home",
    COMING_SOON: "ComingSoon",
    CHAT: "Chat",
    TRENDS: "Trends",
    TIMELINE: "Timeline",
    DISCOVER: "Discover",
    PROFILE: "Profile",
    SETTINGS: "Settings",
    SETTING_CHANGE: "SettingChange",
    FEEDBACK: "Feedback",
}